### PR TITLE
Reuse arel clause in ::hstore_element_missing

### PR DESCRIPTION
**Pull request by rthbound**
- avoiding repeated code (DRY)

### CODE REVIEW

**Comment by king601** [comment]
Thanks for this @rthbound, great change IMO :)

**Comment by Jaehdawg** [comment]
👍

**Comment by chevinbrown** [comment]
// @ProctorU/engineering What do I need to do to get these many reviews? 😄

**Comment by king601** [comment]
Kolaches @chevinbrown.

**Pull request merged**
